falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/custom_rules.yaml  # this will use the file we created

  customRules:
    custom_rules.yaml: |-
      {{ .Files.Get "custom-falco-rules.yaml" | indent 2 }}

  metrics:
    enabled: true
    interval: 10s
    webserver:
      enabled: true
      listen: "0.0.0.0"
      port: 8765
      prometheus_metrics_enabled: true  # âœ… must be exactly here

  falcosidekick:
    enabled: false
